import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { parseConfig } from "../../src/engine/config";
import { SKILL_NAMES } from "../../src/host/claude";
import { CODEX_DIR, codexSkillPath, renderCodexSkill, writeCodex } from "../../src/host/codex";

const CONFIG = parseConfig(
  {
    version: 1,
    roots: [{ path: "apps/api", lang: "typescript" }],
    packs: { typescript: { version: "^1" } },
  },
  "a test config",
);

let repo: string;

beforeEach(() => {
  repo = mkdtempSync(join(tmpdir(), "empo-codex-"));
});

afterEach(() => {
  rmSync(repo, { recursive: true, force: true });
});

function read(path: string): string {
  return readFileSync(join(repo, path), "utf8");
}

function seed(path: string, content: string): void {
  const target = join(repo, path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, "utf8");
}

describe("renderCodexSkill", () => {
  test("retains the shared workflow body with Codex-compatible frontmatter", () => {
    for (const name of SKILL_NAMES) {
      const skill = renderCodexSkill(name, CONFIG);
      const frontmatter = skill.slice(0, skill.indexOf("---", 4) + 3);

      expect(frontmatter.split("\n")).toEqual([
        "---",
        expect.stringMatching(/^name: /),
        expect.stringMatching(/^description: /),
        "---",
      ]);
      expect(skill).toContain("Generated by `empo update` from this repository's EmPo config.");
    }
  });
});

describe("writeCodex", () => {
  test("writes exactly the three owned skill files in deterministic order", () => {
    expect(writeCodex(repo, CONFIG)).toEqual(
      SKILL_NAMES.map((name) => ({ path: codexSkillPath(name), state: "created" })),
    );

    for (const name of SKILL_NAMES) {
      expect(read(codexSkillPath(name))).toBe(renderCodexSkill(name, CONFIG));
    }
  });

  test("is idempotent", () => {
    writeCodex(repo, CONFIG);

    expect(writeCodex(repo, CONFIG)).toEqual(
      SKILL_NAMES.map((name) => ({ path: codexSkillPath(name), state: "unchanged" })),
    );
  });

  test("regenerates an owned skill edited by hand", () => {
    writeCodex(repo, CONFIG);
    seed(codexSkillPath("empo-query"), "mine now\n");

    const written = writeCodex(repo, CONFIG);

    expect(written[0]).toEqual({ path: codexSkillPath("empo-query"), state: "updated" });
    expect(read(codexSkillPath("empo-query"))).toBe(renderCodexSkill("empo-query", CONFIG));
  });

  test("refuses a symbolic link at an owned skill file", () => {
    const outside = join(repo, "..", "outside-skill.md");
    writeFileSync(outside, "outside\n");
    const target = join(repo, codexSkillPath("empo-query"));
    mkdirSync(dirname(target), { recursive: true });
    symlinkSync(outside, target);

    expect(() => writeCodex(repo, CONFIG)).toThrow(
      "Refusing to write Codex skill through symbolic link",
    );
    expect(readFileSync(outside, "utf8")).toBe("outside\n");
  });

  test("refuses a symbolic link at an owned skill directory", () => {
    const outside = join(repo, "..", "outside-skill-directory");
    mkdirSync(outside, { recursive: true });
    const target = join(repo, CODEX_DIR, "skills", "empo-query");
    mkdirSync(dirname(target), { recursive: true });
    symlinkSync(outside, target);

    expect(() => writeCodex(repo, CONFIG)).toThrow(
      "Refusing to write Codex skill through symbolic link",
    );
    expect(() => readFileSync(join(outside, "SKILL.md"), "utf8")).toThrow();
  });
});
