import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, test, vi } from "vitest";
import { updateCommand } from "../../src/commands/update";
import { loadConfig } from "../../src/engine/config";
import { EmpoError } from "../../src/errors";
import { AGENTS_PATH, EMPO_BEGIN, EMPO_END, renderAgentsBlock } from "../../src/host/agents";
import { SETTINGS_PATH, SKILL_NAMES, skillPath } from "../../src/host/claude";

/**
 * `empo update` over the acme fixture: regenerate the host instructions from the shipped discipline
 * plus this repository's config.
 *
 * Two properties are the whole command, and both are about restraint. It owns the bytes between its
 * markers and nothing else, because AGENTS.md belongs to the repository and EmPo is a guest in it,
 * so every case here writes prose around the block and demands it back verbatim. And it is
 * idempotent out loud: a generator whose output changes when its inputs did not puts a file in every
 * diff, and a file that appears in every diff is a file nobody reads.
 *
 * What the block *says* is host/agents.ts's spec. What is pinned here is that this command reads
 * this repository's config, hands it to the generator, and reports honestly which of the three
 * things it did.
 */

const fixture = fileURLToPath(new URL("../../fixtures/acme-platform", import.meta.url));

const CONFIG_PATH = ".empo/config.json";

/** A hand-written AGENTS.md, in the two halves that have to survive a regeneration untouched. */
const HUMAN_ABOVE = "# Agent instructions\n\nRun the test suite with `npm test` before you push.\n";
const HUMAN_BELOW = "\n## House style\n\nNo em-dashes. This paragraph is ours.\n";

/** What an older EmPo left between the markers, and what this run has to replace. */
const STALE_BLOCK = "## EmPo\n\nGenerated by a version that shipped before the adapters section.";

const temps: string[] = [];

interface Recorded {
  printed: string;
  thrown: unknown;
}

/** One run of a command, with everything it printed and whatever it threw kept side by side. */
function record(body: () => void): Recorded {
  const lines: string[] = [];
  const log = vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    lines.push(args.join(" "));
  });

  let thrown: unknown;
  try {
    body();
  } catch (error) {
    thrown = error;
  } finally {
    log.mockRestore();
  }

  return { printed: lines.join("\n"), thrown };
}

/** Everything the command printed, joined, so a test can look for one line in it. */
function capture(body: () => void): string {
  const { printed, thrown } = record(body);
  if (thrown !== undefined) throw thrown;
  return printed;
}

function expectEmpoError(exitCode: number, body: () => void): EmpoError {
  const { thrown } = record(body);
  expect(thrown, `expected a EmpoError with exit code ${exitCode}`).toBeInstanceOf(EmpoError);
  expect((thrown as EmpoError).exitCode).toBe(exitCode);
  return thrown as EmpoError;
}

/** The fixture, config and all. update reads a config and writes one file, so nothing else matters. */
function checkout(): string {
  const repo = mkdtempSync(join(tmpdir(), "empo-update-"));
  cpSync(fixture, repo, { recursive: true });
  temps.push(repo);
  return repo;
}

/** A directory with no EmPo config at all, which is the one thing update cannot work without. */
function repoWithoutConfig(): string {
  const repo = mkdtempSync(join(tmpdir(), "empo-update-bare-"));
  writeFileSync(join(repo, "README.md"), "# acme-platform\n");
  temps.push(repo);
  return repo;
}

function agents(repo: string): string {
  return readFileSync(join(repo, AGENTS_PATH), "utf8");
}

function writeAgentsFile(repo: string, contents: string): void {
  writeFileSync(join(repo, AGENTS_PATH), contents, "utf8");
}

/** The block EmPo would generate for this repository, from the config the command will read. */
function expectedBlock(repo: string): string {
  return renderAgentsBlock(loadConfig(repo).config);
}

function editConfig(repo: string, edit: (config: Record<string, unknown>) => void): void {
  const path = join(repo, CONFIG_PATH);
  const config = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  edit(config);
  writeFileSync(path, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

afterEach(() => {
  vi.restoreAllMocks();
  for (const dir of temps.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe("the managed block", () => {
  test("creates the file when there is none, and names this repository's roots", () => {
    const repo = checkout();
    expect(existsSync(join(repo, AGENTS_PATH))).toBe(false);

    const printed = capture(() => {
      updateCommand(repo);
    });

    expect(printed).toContain(join(repo, CONFIG_PATH));
    expect(printed).toContain(`host       created   ${AGENTS_PATH}`);
    expect(printed).toContain("OK  host instructions regenerated from this config");

    // Both host targets, because `empo update` regenerating only AGENTS.md is exactly the state
    // this was once left in, and a repository whose hooks silently stopped being written would look
    // healthy right up until nothing gated a commit (docs/10-distribution.md).
    expect(printed).toContain(`host       created   ${SETTINGS_PATH}`);
    for (const name of SKILL_NAMES) {
      expect(printed).toContain(`host       created   ${skillPath(name)}`);
      expect(existsSync(join(repo, skillPath(name)))).toBe(true);
    }
    expect(existsSync(join(repo, SETTINGS_PATH))).toBe(true);

    // Nothing was removed, so the note that names removed hook entries stays quiet. It is the
    // ordinary run and an ordinary run has nothing to report.
    expect(printed).not.toContain("empo hook entry");
    expect(printed).not.toContain("empo hook entries");

    // Generated from this config rather than shipped as static text, which is the reason the
    // command exists: a hand-written file would say "configure a tracker" where this one says
    // there is none, so ticket-fit grading is skipped.
    const written = agents(repo);
    expect(written).toContain("- `apps/api` (php, laravel)");
    expect(written).toContain("- `apps/mobile` (typescript, react-native)");
    expect(written).toContain(expectedBlock(repo));
  });

  test("replaces its own block and leaves every byte outside the markers alone", () => {
    // The case this protects: a repository that already had an AGENTS.md a human wrote. EmPo owns
    // what is between its markers and nothing else.
    const repo = checkout();
    writeAgentsFile(
      repo,
      `${HUMAN_ABOVE}\n${EMPO_BEGIN}\n${STALE_BLOCK}\n${EMPO_END}\n${HUMAN_BELOW}`,
    );

    const printed = capture(() => {
      updateCommand(repo);
    });

    const written = agents(repo);
    expect(printed).toContain(`host       updated   ${AGENTS_PATH}`);
    // Two host targets now, so the closing line can no longer speak of "the file". It names what
    // empo owns in each: the marker block in one, the hook entries it wrote in the other.
    expect(printed).toContain("only the block between the empo markers changed");
    expect(printed).toContain("The rest of both is yours");

    expect(written.startsWith(HUMAN_ABOVE)).toBe(true);
    expect(written.endsWith(HUMAN_BELOW)).toBe(true);
    expect(written).not.toContain(STALE_BLOCK);

    // Exactly one pair of markers, still, and the current block between them.
    expect(written.split(EMPO_BEGIN)).toHaveLength(2);
    expect(written.split(EMPO_END)).toHaveLength(2);
    const between = written.slice(
      written.indexOf(EMPO_BEGIN) + EMPO_BEGIN.length,
      written.indexOf(EMPO_END),
    );
    expect(between.trim()).toBe(expectedBlock(repo).trim());
  });
});

describe("running it twice in a row", () => {
  test("reports unchanged the second time and does not rewrite the file", () => {
    // What makes this safe to run from a hook or a CI step: it never dirties a checkout it has
    // nothing to change. The bytes and the mtime are both asserted, because a rewrite with
    // identical content is still a write, and it is what puts the file in a diff.
    const repo = checkout();
    writeAgentsFile(repo, `${HUMAN_ABOVE}\n${EMPO_BEGIN}\n${STALE_BLOCK}\n${EMPO_END}\n`);
    capture(() => {
      updateCommand(repo);
    });
    const before = agents(repo);
    const mtime = statSync(join(repo, AGENTS_PATH)).mtimeMs;

    const printed = capture(() => {
      updateCommand(repo);
    });

    expect(printed).toContain(`host       unchanged ${AGENTS_PATH}`);
    expect(printed).toContain("OK  host instructions already match this config");
    expect(printed).not.toContain("regenerated");
    expect(agents(repo)).toBe(before);
    expect(statSync(join(repo, AGENTS_PATH)).mtimeMs).toBe(mtime);
  });
});

describe("when the config changes", () => {
  test("the next run says what the new tracker means for a review", () => {
    const repo = checkout();
    capture(() => {
      updateCommand(repo);
    });

    // The fixture configures no adapters, so the block starts by saying grading is skipped. That
    // absence is a fact about the repository, and it has to stop being stated the moment it stops
    // being true, or an agent is told to skip the grading a tracker now makes possible.
    expect(agents(repo)).toContain("Tracker: none configured");
    expect(agents(repo)).not.toContain("`mcp`");

    editConfig(repo, (config) => {
      config.adapters = {
        tracker: { kind: "mcp", host: "jira", project: "ACME", keyPattern: "ACME-\\d+" },
      };
    });

    const printed = capture(() => {
      updateCommand(repo);
    });

    expect(printed).toContain(`host       updated   ${AGENTS_PATH}`);
    const written = agents(repo);
    // `backed by jira` and not just `mcp`: `host` exists to be printed, and a block that named only
    // the kind would tell an agent to fetch a ticket without saying which connector to fetch it
    // with, which is the one job that field has (docs/03-config-schema.md).
    expect(written).toContain("Tracker: `mcp`, backed by jira, project `ACME`");
    expect(written).toContain("ticket keys matching `ACME-\\d+`");
    expect(written).toContain("Read the ticket and every comment on it");
    expect(written).not.toContain("Tracker: none configured");
    expect(written).toContain(expectedBlock(repo));
  });
});

describe("a repository with no EmPo config", () => {
  test("exits 2 with the message that names empo init", () => {
    // The honest answer to "regenerate instructions from this config" when there is no config, and
    // a usage error rather than a gate failure: nothing was judged, so nothing failed.
    const repo = repoWithoutConfig();

    const error = expectEmpoError(2, () => {
      updateCommand(repo);
    });

    expect(error.message).toBe("No EmPo config found");
    expect(error.details.join("\n")).toContain("Run empo init to create one.");
    expect(existsSync(join(repo, AGENTS_PATH))).toBe(false);
  });
});
