import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { forgeSlug } from "../adapters/forge/types";
import { configError, type EmpoError } from "../errors";
import type { EmpoConfig, EmpoForge, EmpoTracker } from "../schema/config.schema";

/**
 * The host instruction file (docs/10-distribution.md, `empo update` in docs/06-cli.md). It is
 * generated rather than shipped as one static markdown file for the reason that whole section
 * gives: the useful half of these instructions is what *this* repository looks like, which forge
 * and tracker it really has, and therefore what a review can and cannot know. A hand-written file
 * would say "configure a tracker" where a generated one says "there is none, so ticket-fit grading
 * is skipped, do not invent criteria."
 *
 * Two design rules hold the file together.
 *
 * **EmPo owns what is between its markers and nothing else.** Many repositories already have an
 * AGENTS.md a human wrote. Regenerating it wholesale would delete their work, so the block is
 * merged in: appended once if there are no markers, replaced in place if there are.
 *
 * **The review discipline is not duplicated here.** The block says that `empo review` prints the
 * discipline and that the agent runs what it prints. A second copy would drift from
 * src/discipline/review.md, and that copy is the one the verification gate is built around, so a
 * drifted copy would teach an agent a workflow the gate does not implement.
 */

export const EMPO_BEGIN = "<!-- empo:begin -->";
export const EMPO_END = "<!-- empo:end -->";

/** Repo-relative, and the name every host that reads a plain instruction file looks for. */
export const AGENTS_PATH = "AGENTS.md";

/** The managed block: everything between the markers, markers excluded. */
export function renderAgentsBlock(config: EmpoConfig): string {
  return [
    "## EmPo",
    "",
    "This section is generated by `empo update` from this repository's EmPo config. Everything",
    "between the markers is replaced on the next run; everything outside them is yours.",
    "",
    "### This repository, as EmPo sees it",
    "",
    ...rootLines(config),
    "",
    "Curated knowledge lives in `.empo/`: `flows.json` holds the end-user journeys, `spines/` holds",
    "the critical chains and their invariants, and `conventions.md` is the false-positive register a",
    "review reads before it flags anything. All three are human-owned. Propose changes to them as a",
    "diff for a human to approve, never as a fait accompli.",
    "",
    "### Adapters",
    "",
    ...adapterLines(config, "full"),
    "",
    "### Commands",
    "",
    // One row per command an agent invokes itself, ordered by how often it reaches for one, which
    // is why `empo init` and `empo pack test` sit at the bottom rather than in alphabetical or
    // registration order: both are real agent actions and neither is a daily one.
    //
    // `empo hook` is the one registered command deliberately left out, and the omission is the rule
    // rather than an oversight. Its caller is the host and not a person or an agent: it reads a hook
    // payload on stdin and prints nothing at all when everything is well, so an agent that runs it
    // by hand either waits on a stdin nobody is writing or answers a payload it invented, and gets
    // silence back either way. Every gate it fires is one of the rows below run over the same code,
    // so listing it would add no answer an agent cannot already get, and would add one command whose
    // first use teaches that a EmPo command can hang.
    //
    // That omission is stated in the rendered block too, in the one sentence below the table, for
    // the reason this comment cannot serve: an agent reads AGENTS.md and never reads this file, and
    // a bare table gives it no way to tell a deliberate absence from a forgotten row. It finds
    // `empo hook` in `empo --help` sooner or later, and the cheapest moment to be told not to run it
    // is before it hangs on a stdin nobody is writing. One sentence and no more, because this block
    // is read on every session and every line of it is paid for on every session.
    //
    // `empo init` earns its row despite being scaffolding on first run, because its second phase is
    // the gate an agent's proposed flows and spines pass through, and that phase runs in a
    // repository somebody initialized months ago. Leaving it out would leave the mapping work with
    // no command named anywhere an agent reads before it starts. The row names the `--proposal`
    // form rather than the bare command for the same reason: a repository holding this block has
    // been scaffolded already, so the phase an agent still has ahead of it is the gate.
    "| command | what it is for |",
    "| ------- | -------------- |",
    "| `empo index` | Rebuild the graph from source, after the code moved. |",
    "| `empo query [<symbol>]` | Blast radius: fan-in, flows reached, blind flows, coverage. |",
    "| `empo review [<pr>]` | Print the review brief and the discipline to run over it. |",
    "| `empo check` | Commit gate: a guarded file changed with no value-asserting test. |",
    "| `empo verify` | Resolve every spine citation against source and report drift. |",
    "| `empo doctor` | Health: staleness, config validity, unmapped directories, adapters. |",
    "| `empo update` | Regenerate this section. |",
    "| `empo init --proposal <path>` | Gate a proposed flow and spine map; `--apply` writes it. |",
    "| `empo pack test <name>` | Run a language pack against its fixtures, after editing it. |",
    "",
    "`empo hook` is registered and left out of that table on purpose: the host calls it with a payload",
    "on stdin, so running it by hand waits on a stdin nobody is writing.",
    "",
    "Ask `empo query` rather than grepping for consumers and guessing: that is what the graph is for.",
    "Its answer is a floor and not a ceiling, because reflection, dynamic dispatch and configuration",
    "add reach no static graph can see, so say that out loud when you report a blast radius. When an",
    "answer looks wrong, `empo doctor` is the first thing to run: a stale graph answers about code",
    "that has moved.",
    "",
    "### Two rules you must not get wrong",
    "",
    "**`.empo/generated/` is machine-owned.** Only `empo index` writes it. Never hand-edit a file",
    "under it and never patch one to make an answer come out the way you expected: an edited graph",
    "produces an impact answer that looks generated and is invented, which is the single failure",
    "this tool exists to prevent. If an answer is wrong, fix the config or the pack, then reindex.",
    "",
    "**A guarded file needs a value-asserting test.** Each spine lists `guarded` globs. If a change",
    "touches one of them and adds no test line asserting an exact value, `empo check` exits 1 and",
    "names the spine, the file and the terms it wanted. A spine may also name the test files that",
    "count, in `assertionPaths`, and the failure prints those too: write the test where it asks, not",
    "wherever is convenient. The way through is the test, not a smaller",
    "diff. Overriding it takes an explicit reason on the record, and unstaging the spine file does",
    "not dodge it: the spines are read from disk.",
    "",
    "### The review discipline lives in one place",
    "",
    "`empo review` prints the full discipline beneath the brief: the pipeline, the two invariants (a",
    "review executes nothing and disturbs nothing), and the verification gate every finding has to",
    "survive before the author sees it. Run what it prints. Do not improvise a review from this",
    "section, and do not copy the discipline into another file: the copy `empo review` hands you is",
    "the one the gate is built around, and a second copy drifts from it.",
  ].join("\n");
}

/**
 * One line per root, because "which directory is which language" is the fact an agent gets wrong
 * most often in a monorepo, and the framework is worth naming where a root declares one: it is what
 * decides which framework-specific extractors ran.
 */
function rootLines(config: EmpoConfig): string[] {
  return [
    "Roots, each indexed by one language pack:",
    "",
    ...config.roots.map((root) => {
      const framework = root.framework === undefined ? "" : `, ${root.framework}`;
      return `- \`${root.path}\` (${root.lang}${framework})`;
    }),
  ];
}

/**
 * How much of the `mcp` protocol a rendering carries.
 *
 * `full` is for the two places an agent reads before it starts work: this file's managed block and
 * the `empo-review` skill. `summary` is for a generated file about something else entirely, where
 * naming the forge is context and the payload protocol is thirty lines of noise between the reader
 * and what they came for.
 *
 * The summary never says less than the truth. It still states that `empo review` will stop and ask
 * for a payload, because an agent that meets that stop without expecting it reads it as a failure
 * and starts working around it. What it leaves out is the field mapping, which the request block
 * `empo review` prints carries anyway.
 */
type Detail = "full" | "summary";

/**
 * The adapter section, shared with the generated `.claude/` skills (src/host/claude.ts) rather than
 * written a second time there.
 *
 * These two files used to carry a paraphrase of each other, and by the time `mcp` arrived they had
 * already drifted into saying slightly different things about the same config. That is survivable
 * for a sentence about roots. It is not survivable here: under `mcp` this text is the interface the
 * agent acts on, so a second copy is a second interface, and the one that goes stale is whichever
 * one the next person does not think to open.
 */
export function adapterLines(config: EmpoConfig, detail: Detail): string[] {
  return [...forgeLines(config, detail), "", ...trackerLines(config, detail)];
}

function forgeLines(config: EmpoConfig, detail: Detail): string[] {
  const forge = config.adapters?.forge;
  if (forge === undefined || forge.kind === "local") {
    // `local` is a configured adapter and no adapter degrades to it, so both land here, but only
    // one of them is a decision somebody made. Saying "none configured" over a deliberate `local`
    // would read as a mistake to fix.
    const label = forge === undefined ? "none configured" : "`local`, which is no host at all";
    return [
      `Forge: ${label}, so \`empo review\` reads the local diff against a base ref instead of a`,
      "pull request. There is no PR description, no review comments and no CI result to read, and",
      "nothing can be posted anywhere. Say so in the review rather than leaving the absence implicit.",
    ];
  }

  if (forge.kind === "mcp") return mcpForgeLines(forge, detail);

  // Through forgeSlug and not a second join of the same two fields. Config keeps the workspace and
  // the repo apart, every github tool wants them as `OWNER/REPO`, and a block that spells that
  // location any other way teaches the agent reading it a slug no `gh` call will accept.
  const where = forgeSlug(forge);
  const named = where === undefined ? "" : ` (\`${where}\`)`;
  return [
    `Forge: \`${forge.kind}\`${named}. \`empo review\` reads the pull request, its comments and its`,
    "CI result from there, and posts only when asked to.",
  ];
}

/**
 * The one adapter whose generated text is an interface and not a description.
 *
 * EmPo makes no model call and holds no connector, so under `mcp` it cannot fetch the pull request:
 * the agent reading this can, and `empo review` stops and asks it to. If these lines do not say so,
 * nobody ever writes a payload, the review degrades to a local diff on every run, and the only
 * symptom is a review that is quietly thinner than it should be. So this is the text that has to be
 * right, and it is exact rather than encouraging: the field names, the traps, and what each silence
 * would cost.
 */
function mcpForgeLines(forge: EmpoForge, detail: Detail): string[] {
  // Every interpolation sits at the end of its line, so a long workspace name ragged-edges one line
  // instead of reflowing the paragraph. These files are regenerated on every config change and the
  // diff is read by a human.
  const opening = [
    `Forge: \`mcp\`, backed by ${backing(forge.host)}${located(forge)}.`,
    "EmPo holds no connector and makes no network call, so it cannot fetch that pull request itself.",
    "`empo review <id>` stops before the review and prints a request block: the file to write, the",
    "exact JSON it wants, and the command to run next.",
    // On its own line and kept there. Markdown reflows it into the paragraph either way, and the
    // one sentence that stops an agent treating phase 0 as a failure should be greppable whole.
    "**That stop is the normal path and not an error.**",
    `Fetch the pull request with ${tools(forge.host, "pull request")},`,
    "write the file where it says, and run the command it printed.",
  ];
  if (detail === "summary") return opening;

  return [
    ...opening,
    "",
    // Every line below breaks at a clause boundary, never through one. A flag and its verb, or a
    // noun and its adjective, split across two printed lines costs the reader a reread, and this is
    // the text that is read under time pressure. Markdown reflows it into one paragraph regardless,
    // so the line breaks buy nothing else and may as well fall where they help.
    "What you hand back is checked against this repository before the review believes any of it:",
    "the id has to be the one that was asked for, and both branch names have to resolve to a commit",
    "here, as `<branch>` or as `origin/<branch>`. A pull request that was never opened fails on its",
    "branch names, which is the only reason fetching it yourself is allowed at all.",
    "EmPo does not fetch on your behalf, so run `git fetch` first if the branch is not here yet.",
    "",
    "Four things fail quietly, so each one is worth reading twice:",
    "",
    "- **Do not fetch the diff.** EmPo computes it locally from the two branch names, which is why",
    "  the round trip carries metadata only. Fetching it is the habit to break here, and what comes",
    "  back is redirected, capped at the host's file and line limits, and slower than `git diff`.",
    '- **Write `""` for an empty description, never leave the key out.** A pull request with no',
    "  description is ordinary and common; a field that failed to map is a bug. An omitted key is",
    "  refused, naming the field, which is what keeps those two apart.",
    "- **Omit `ci` rather than name a state you did not read.** Omitted, the brief reports the",
    "  CI state as unknown and the review says the pipeline was not checked. A guessed `passed` is",
    "  a fact in the review that nobody established.",
    "- **Nothing can be posted back.** This adapter has no connector to write with, so `--post` fails.",
    "  If the review is wanted on the pull request itself, post it there yourself with",
    `  ${tools(forge.host, "pull request")}.`,
    "",
    // The house rule this file already applies to the review discipline, applied to the payload.
    // The mapping was in here as a table, confirmed against a live pull request and correct, and it
    // was still the wrong place for it: the request block prints the same table from the code that
    // reads the payload back, so that copy cannot drift from what empo will accept and this one
    // could. Three copies that agree today, with nothing pinning that they keep agreeing, is a
    // guarantee with no owner. docs/09 keeps its copy because it is written for a human deciding
    // whether to trust the design, which is a different job from being acted on.
    "The field names are not repeated here. The request block prints the exact JSON EmPo accepts,",
    "field by field, and for a host with a confirmed mapping it prints where each field comes from",
    "in that host's own response, along with what to omit and why. Take them from there rather than",
    "from this file or from memory: that copy is printed by the code that reads the payload back,",
    "so it cannot drift from what will be accepted, and a second copy here could.",
  ];
}

function trackerLines(config: EmpoConfig, detail: Detail): string[] {
  const tracker = config.adapters?.tracker;
  if (tracker === undefined || tracker.kind === "none") {
    const label = tracker === undefined ? "none configured" : "`none`";
    return [
      `Tracker: ${label}, so \`empo review\` skips ticket-fit grading and says so. Do not`,
      "invent acceptance criteria to grade against: a review that grades a change on criteria",
      "nobody wrote reports agreement with itself.",
    ];
  }

  if (tracker.kind !== "mcp") {
    return [
      `Tracker: \`${tracker.kind}\`${describes(tracker)}. Read the ticket and every comment on it`,
      "before you open the diff, and grade the change against the criteria it states.",
    ];
  }

  const opening = [
    `Tracker: \`mcp\`, backed by ${backing(tracker.host)}${describes(tracker)}.`,
    "The same request block asks for the ticket, so the round trip is one and not two: EmPo extracts",
    "the key from the branch, the title and the description, and names the key it wants.",
    `Fetch it with ${tools(tracker.host, "ticket")}.`,
    "Read the ticket and every comment on it before you open the diff, and grade the change against",
    "the criteria it states.",
  ];
  if (detail === "summary") return opening;

  return [
    ...opening,
    "",
    "- **Echo the key EmPo asked for back, verbatim, in `key`.** It is the only check there is on a",
    "  ticket: nothing in this repository knows what the ticket says, so a payload whose `key` is",
    "  not the key that was asked for is a payload for some other ticket, and ticket-fit goes",
    "  ungraded. The host's own identifier and its permalink belong in `url`. Fetching a task by a",
    "  numeric id and then writing that id into `key` is how this goes wrong, and it reads as a",
    "  missing ticket rather than as the mistake it is.",
    "- **Leave `criteria` out unless the ticket states some.** Absent means EmPo derives them from",
    "  the body, which is what every other tracker does. `[]` is the claim that the ticket states",
    "  none, and the review reports that as a fact about the ticket.",
  ];
}

/** `workspace` and `repo` named rather than run together: the host call needs to know which is which. */
function located(forge: EmpoForge): string {
  const where = [
    forge.workspace === undefined ? null : `workspace \`${forge.workspace}\``,
    forge.repo === undefined ? null : `repository \`${forge.repo}\``,
  ].filter((one) => one !== null);
  return where.length === 0 ? "" : `, ${where.join(", ")}`;
}

function describes(tracker: EmpoTracker): string {
  const project = tracker.project === undefined ? "" : `, project \`${tracker.project}\``;
  const pattern =
    tracker.keyPattern === undefined ? "" : `, ticket keys matching \`${tracker.keyPattern}\``;
  return `${project}${pattern}`;
}

/**
 * `adapters.*.host` is the only thing in the config that exists to be printed, and this and `tools`
 * below are where it is printed. An `mcp` adapter that names no host still works, so both degrade to
 * a generic noun: "your pull request tool" sends an agent to look at what it has, where a guessed
 * name would send it confidently to the wrong connector.
 *
 * Echoed verbatim, never title-cased and never matched against a list of hosts EmPo knows. It is
 * free text a human wrote, so theirs is the only spelling certain to be right, and a config saying
 * "bitbucket server" has to survive as "bitbucket server".
 */
function backing(host: string | undefined): string {
  return named(host) ?? "a host this config does not name";
}

function tools(host: string | undefined, generic: string): string {
  const name = named(host);
  // Spelled the way the request block in src/commands/review.ts spells it, so an agent that reads
  // both is not left wondering whether "your bitbucket tool" and "your bitbucket tools" are two
  // different things it is being sent to.
  return name === null ? `your ${generic} tool` : `your ${name} tool`;
}

function named(host: string | undefined): string | null {
  return host === undefined || host.trim() === "" ? null : host.trim();
}

/** What a repository with no AGENTS.md gets above the block. Short: the block speaks for itself. */
const HEADING = [
  "# Agent instructions",
  "",
  "Instructions for AI agents working in this repository.",
];

/** Replace the managed block in `existing`, preserving every byte outside it. */
export function mergeAgents(existing: string | null, block: string): string {
  const wrapped = `${EMPO_BEGIN}\n${block}\n${EMPO_END}`;

  // An empty or whitespace-only file has nothing to preserve, so it is treated as a new one and
  // gets the heading too.
  if (existing === null || existing.trim() === "") return `${HEADING.join("\n")}\n\n${wrapped}\n`;

  const begins = occurrences(existing, EMPO_BEGIN);
  const ends = occurrences(existing, EMPO_END);
  const begin = existing.indexOf(EMPO_BEGIN);
  const end = existing.indexOf(EMPO_END);

  // No markers at all: a hand-written AGENTS.md. Append, never replace. This runs once; every later
  // run finds the markers it just wrote and takes the branch below.
  if (begins === 0 && ends === 0) {
    const separator = existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
    return `${existing}${separator}${wrapped}\n`;
  }

  // Anything other than exactly one pair in order, and EmPo cannot tell which bytes are its own.
  // Both silent answers are wrong: replacing the first pair leaves a stale second copy of the very
  // instructions this block exists to keep current, and replacing from the first marker to the last
  // one deletes whatever a human wrote between the pairs. So it refuses and names the fix.
  if (begins !== 1 || ends !== 1 || end < begin) throw malformed(begins, ends);

  return existing.slice(0, begin) + wrapped + existing.slice(end + EMPO_END.length);
}

export function writeAgents(
  repoRoot: string,
  config: EmpoConfig,
): { path: string; state: "created" | "updated" | "unchanged" } {
  const target = join(repoRoot, AGENTS_PATH);
  const existing = existsSync(target) ? readFileSync(target, "utf8") : null;
  const merged = mergeAgents(existing, renderAgentsBlock(config));

  // Byte-identical means there is nothing to do, and saying so is what makes `empo update` safe to
  // run from a hook or a CI step: it never dirties a checkout it has nothing to change.
  if (existing === merged) return { path: AGENTS_PATH, state: "unchanged" };

  writeFileSync(target, merged, "utf8");
  return { path: AGENTS_PATH, state: existing === null ? "created" : "updated" };
}

function occurrences(text: string, marker: string): number {
  return text.split(marker).length - 1;
}

function malformed(begins: number, ends: number): EmpoError {
  return configError(`${AGENTS_PATH} carries a malformed EmPo block, so nothing was written`, [
    `Found ${begins} "${EMPO_BEGIN}" and ${ends} "${EMPO_END}".`,
    "EmPo replaces exactly one pair, in that order, and leaves every other byte alone.",
    "Keep the block you want, delete the stray markers, and run empo update again.",
  ]);
}
